advanced/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views 
from . views import HomeView,BlogCreateView,AllBlogView,BlogDetailView,BlogUpdateView,BlogDeleteView
from django.contrib.auth import views as auth_view

app_name = 'blog'

urlpatterns = [
	path('', HomeView.as_view(), name = 'home'),
	path('blog-create/', BlogCreateView.as_view(), name = 'create_blog'),
	path('login/', auth_view.LoginView.as_view(template_name = 'blog/login.html'), name = 'login'),
	path('logout/', auth_view.LogoutView.as_view(template_name = 'blog/logout.html'), name = 'logout'),
	path('all-blogs/',AllBlogView.as_view(), name = 'all-blogs'),
	path('<int:pk>/detail/', BlogDetailView.as_view(), name = 'detail'),
	path('<int:pk>/update/',BlogUpdateView.as_view(),name = 'blog-update'),
	path('<int:pk>/delete/', BlogDeleteView.as_view(),name = 'blog-delete'),
	path('signup/', views.sign_up, name = 'signup'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 

class Blog(models.Model):
	title = models.CharField(max_length = 200)
	content = models.TextField()
	author  = models.ForeignKey(User, on_delete = models.CASCADE)

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs ={'pk':self.pk})

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms  


class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length = 200)
	last_name = forms.CharField(max_length = 200)
	email = forms.EmailField()

	class Meta:
		model = User 
		fields = (
				'username','first_name',
				'last_name','email',
				'password1','password2',
			)

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView,UpdateView,DeleteView
from django.views.generic.edit import * 
from . models import Blog
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.urls import reverse_lazy,reverse
from . models import User 
from . forms import SignUpForm
from django.http import HttpResponseRedirect

####



class HomeView(TemplateView):
	template_name = 'blog/home.html'


class BlogCreateView(LoginRequiredMixin,CreateView):
	template_name = 'blog/blog_create.html'
	model = Blog 
	fields = ['title', 'content']
	

	def form_valid(self,form):
		form.instance.author = self.request.user 
		return super().form_valid(form)

class AllBlogView(ListView):
	model = Blog 
	template_name = 'blog/all_blogs.html'

class BlogDetailView(DetailView):
	model = Blog 
	template_name = 'blog/blog_details.html'

class BlogUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
	model = Blog 
	fields = ['title', 'content']
	template_name = 'blog/blog_update.html'
	
	def form_valid(self,form):
		form.instance.author = self.request.user
		return super().form_valid(form)
	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False
class BlogDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
	model = Blog
	template_name = 'blog/blog_delete.html'
	success_url = reverse_lazy('blog:home') 
	def test_func(self):
		post = self.get_object()
		if(self.request.user == post.author):
			return True 
		return False	
	
def sign_up(request):
	if(request.method == 'POST'):
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('blog:home'),)
	else:
		form = SignUpForm()
	return render(request, 'blog/sign_up.html', {'form':form})
				


	

blog/templates/blog/all_blogs.html
<ul>
	{% for blog in object_list %}
		<li>{{blog.title}}</li>
	{% endfor %}
</ul>	

blog/templates/blog/blog_create.html
<h3>Create Blog</h3>
<form method = 'post'>
	{% csrf_token %}
	{{form.as_p}}
	<button type = 'submit'>Create</button>
</form>

blog/templates/blog/blog_delete.html
<form method = 'post'>
	{% csrf_token %}
	<h3>Delete Blog</h3>
	Do you want to delete this Blog?
	<button type = 'submit'>Yes</button>
</form>	

blog/templates/blog/blog_details.html
{{object.title}}
<br>
{{object.content}}

blog/templates/blog/blog_update.html
<h3>Update!</h3>
<form method = 'post'>
	{% csrf_token %}
	{{form.as_p}}
	<button type = 'submit'>Update</button>
</form>

blog/templates/blog/home.html
<html>
<body>
	<h3>Welcome Back</h3>
</body>
</html>

{% if request.user.is_authenticated %}
	<a href = "{% url 'blog:all-blogs' %}">All Blogs</a>
	<a href = "{% url 'blog:login' %}">Login</a>
	<a href = "{% url 'blog:logout' %}">Logout</a>
{% else %}
	<a href = "{% url 'blog:all-blogs' %}">All Blogs</a>
	<a href = "{% url 'blog:login' %}">Login</a>
	<a href = "{% url 'blog:signup' %}">Signup</a>

{% endif %}	

blog/templates/blog/login.html
<h3>Log In</h3>
<form method = 'post'>
	{% csrf_token %}
	{{form.as_p}}
	<button type = 'submit'>Login</button>
</form>

blog/templates/blog/logout.html
<h3>You were succesfully Logged Out!</h3>

blog/templates/blog/sign_up.html
<h3>Signup Free!</h3>
<form method = 'post'>
	{% csrf_token %}
	{{form.as_p}}
	<button type = 'method '>Signup</button>
</form>